# Generated by Django 2.0.5 on 2018-08-22 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockprices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prices',
            options={'managed': False},
        ),
    ]
