# Generated by Django 2.0.5 on 2018-08-22 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockprices', '0002_auto_20180822_2258'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prices',
            table='Prices',
        ),
    ]
