# Generated by Django 2.0.5 on 2018-08-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockprices', '0004_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='Username', max_length=15)),
                ('email', models.EmailField(db_column='Email', max_length=254)),
                ('password', models.CharField(db_column='Password', max_length=15)),
            ],
            options={
                'managed': False,
                'db_table': 'User',
            },
        ),
    ]
